// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.0";

// src/lib/mcp/tools/list-discussions.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-discussions.ts
var list_discussions_default = defineTool({
  name: "list_discussions",
  title: "List discussions",
  description: "List discussion topics on the platform, newest first. Optionally filter by category or free-text search in title and description.",
  inputSchema: {
    search: z.string().trim().nullable().describe("Free-text search over title and description. Pass null for no search."),
    category: z.string().trim().nullable().describe("Exact category filter, e.g. 'Urban Planning'. Pass null for all categories."),
    limit: z.number().int().min(1).max(50).describe("Maximum number of topics to return (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("topics").select("id, title, slug, category, status, description, proposal, created_at, updated_at").order("created_at", { ascending: false }).limit(limit);
    if (category) query = query.eq("category", category);
    if (search) query = query.or(`title.ilike.%${search}%,description.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) throw new ToolError(error.message);
    const topics = (data ?? []).map((t) => ({
      id: t.id,
      title: t.title,
      slug: t.slug,
      category: t.category,
      status: t.status,
      description: t.description,
      proposal: t.proposal ?? null,
      created_at: t.created_at,
      updated_at: t.updated_at
    }));
    return {
      content: [
        {
          type: "text",
          text: topics.length ? topics.map((t) => `- ${t.title} [${t.category}, ${t.status}] (slug: ${t.slug})`).join("\n") : "No discussions matched."
        }
      ],
      structuredContent: { topics }
    };
  }
});

// src/lib/mcp/tools/get-discussion.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_discussion_default = defineTool2({
  name: "get_discussion",
  title: "Get discussion with posts",
  description: "Read one discussion by slug or id, including its threaded posts with author names, argument types and scores.",
  inputSchema: {
    slug: z2.string().trim().nullable().describe("Topic slug, e.g. 'car-free-friedrichstrasse'. Pass null if using id."),
    id: z2.string().uuid().nullable().describe("Topic id. Pass null if using slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug, id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    if (!slug && !id) throw new ToolError2("Provide either slug or id");
    const supabase = supabaseForUser(ctx);
    const topicQuery = supabase.from("topics").select("id, title, slug, category, status, description, proposal, created_at, updated_at");
    const { data: topic, error: topicError } = id ? await topicQuery.eq("id", id).maybeSingle() : await topicQuery.eq("slug", slug).maybeSingle();
    if (topicError) throw new ToolError2(topicError.message);
    if (!topic) throw new ToolError2("Discussion not found");
    const { data: posts, error: postsError } = await supabase.from("posts").select("id, content, author_id, argdown_type, score, depth, parent_post_id, created_at").eq("topic_id", topic.id).order("created_at", { ascending: true });
    if (postsError) throw new ToolError2(postsError.message);
    const authorIds = [...new Set((posts ?? []).map((p) => p.author_id))];
    const names = /* @__PURE__ */ new Map();
    if (authorIds.length) {
      const { data: profiles } = await supabase.from("profiles").select("user_id, display_name").in("user_id", authorIds);
      for (const p of profiles ?? []) names.set(p.user_id, p.display_name);
    }
    const postList = (posts ?? []).map((p) => ({
      id: p.id,
      content: p.content,
      author: names.get(p.author_id) ?? "Unknown",
      argdown_type: p.argdown_type ?? null,
      score: p.score,
      depth: p.depth,
      parent_post_id: p.parent_post_id ?? null,
      created_at: p.created_at
    }));
    const topicJson = {
      id: topic.id,
      title: topic.title,
      slug: topic.slug,
      category: topic.category,
      status: topic.status,
      description: topic.description,
      proposal: topic.proposal ?? null,
      created_at: topic.created_at,
      updated_at: topic.updated_at
    };
    const text = [
      `# ${topicJson.title} [${topicJson.category}, ${topicJson.status}]`,
      topicJson.description,
      topicJson.proposal ? `Proposal: ${topicJson.proposal}` : "",
      "",
      ...postList.map(
        (p) => `${"  ".repeat(p.depth)}[${p.id}] ${p.author}${p.argdown_type ? ` (${p.argdown_type})` : ""} score ${p.score}: ${p.content}`
      )
    ].filter(Boolean).join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { topic: topicJson, posts: postList }
    };
  }
});

// src/lib/mcp/tools/get-discussion-insights.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@3.0.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_discussion_insights_default = defineTool3({
  name: "get_discussion_insights",
  title: "Get deliberation insights",
  description: "Read the cached deliberation analysis for a discussion: summary, tensions, argument clusters, open questions and contribution guidance.",
  inputSchema: {
    topic_id: z3.string().uuid().describe("Topic id, as returned by list_discussions or get_discussion.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ topic_id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("ai_analyses").select("content, created_at, analysis_type").eq("topic_id", topic_id).eq("analysis_type", "full").order("created_at", { ascending: false }).limit(1).maybeSingle();
    if (error) throw new ToolError3(error.message);
    if (!data) {
      return {
        content: [
          {
            type: "text",
            text: "No deliberation analysis exists yet for this discussion. It can be generated in the app's Insights panel."
          }
        ],
        structuredContent: { analysis: null }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data.content) }],
      structuredContent: {
        created_at: data.created_at,
        analysis: data.content
      }
    };
  }
});

// src/lib/mcp/tools/create-post.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@3.0.0";
import { z as z4 } from "npm:zod@^3.25.76";
var argdownTypes = [
  "claim",
  "support",
  "objection",
  "concern",
  "alternative",
  "question",
  "proposal",
  "evidence",
  "rebuttal"
];
var create_post_default = defineTool4({
  name: "create_post",
  title: "Post a contribution",
  description: "Post a contribution as the signed-in user: a top-level post in a discussion, or a reply to an existing post.",
  inputSchema: {
    topic_id: z4.string().uuid().describe("Topic id the contribution belongs to."),
    content: z4.string().trim().min(2).describe("The contribution text."),
    parent_post_id: z4.string().uuid().nullable().describe("Post id to reply to, or null for a top-level post."),
    argdown_type: z4.enum(argdownTypes).nullable().describe("Argument type of the contribution, or null.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ topic_id, content, parent_post_id, argdown_type }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError4("Authenticated user required");
    const supabase = supabaseForUser(ctx);
    let depth = 0;
    if (parent_post_id) {
      const { data: parent, error: parentError } = await supabase.from("posts").select("depth, topic_id").eq("id", parent_post_id).maybeSingle();
      if (parentError) throw new ToolError4(parentError.message);
      if (!parent) throw new ToolError4("Parent post not found");
      if (parent.topic_id !== topic_id) throw new ToolError4("Parent post belongs to a different discussion");
      depth = parent.depth + 1;
    }
    const { data, error } = await supabase.from("posts").insert({
      topic_id,
      author_id: userId,
      content,
      parent_post_id: parent_post_id ?? null,
      argdown_type: argdown_type ?? null,
      depth
    }).select("id, content, depth, argdown_type, created_at").single();
    if (error) throw new ToolError4(error.message);
    return {
      content: [{ type: "text", text: `Posted contribution ${data.id}.` }],
      structuredContent: {
        post: {
          id: data.id,
          content: data.content,
          depth: data.depth,
          argdown_type: data.argdown_type ?? null,
          created_at: data.created_at
        }
      }
    };
  }
});

// src/lib/mcp/tools/create-discussion.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@3.0.0";
import { z as z5 } from "npm:zod@^3.25.76";
function slugify(title) {
  const base = title.toLowerCase().replace(/ä/g, "ae").replace(/ö/g, "oe").replace(/ü/g, "ue").replace(/ß/g, "ss").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60);
  const suffix = Math.random().toString(36).slice(2, 7);
  return `${base || "discussion"}-${suffix}`;
}
var create_discussion_default = defineTool5({
  name: "create_discussion",
  title: "Create a discussion",
  description: "Create a new discussion topic as the signed-in user, with a title, description, category and optional concrete proposal.",
  inputSchema: {
    title: z5.string().trim().min(3).describe("Discussion title."),
    description: z5.string().trim().describe("What the discussion is about. Pass an empty string if unknown."),
    category: z5.string().trim().describe("Category label, e.g. 'Urban Planning'."),
    proposal: z5.string().trim().nullable().describe("A concrete proposal under debate, or null.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, description, category, proposal }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError5("Not authenticated");
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError5("Authenticated user required");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("topics").insert({
      title,
      description,
      category,
      proposal: proposal ?? null,
      slug: slugify(title),
      author_id: userId
    }).select("id, title, slug, category, status, description, proposal, created_at").single();
    if (error) throw new ToolError5(error.message);
    return {
      content: [{ type: "text", text: `Created discussion "${data.title}" (slug: ${data.slug}).` }],
      structuredContent: {
        topic: {
          id: data.id,
          title: data.title,
          slug: data.slug,
          category: data.category,
          status: data.status,
          description: data.description,
          proposal: data.proposal ?? null,
          created_at: data.created_at
        }
      }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jzxzixssuvkfbyryozon";
var mcp_default = defineMcp({
  name: "deliberate-space",
  title: "Deliberate Space",
  version: "0.1.0",
  instructions: "Tools for Deliberate Space, a deliberation platform with topics, threaded posts and AI deliberation insights. Use `list_discussions` to find topics, `get_discussion` to read a full thread, `get_discussion_insights` for tensions, clusters and open questions, `create_post` to contribute as the signed-in user, and `create_discussion` to open a new topic.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_discussions_default,
    get_discussion_default,
    get_discussion_insights_default,
    create_post_default,
    create_discussion_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
